Development frontend
aneenajohn/e-commerce-app-with-backend pull request #1
Opened 2021-05-08 18:41 UTC by aneenajohn

Hi,

Thanks for taking time to review the code. This is  a PR for e-commerce site fromt-end. Would be glad to hear your suggestions.

2021-05-14 08:23 UTC, Jaynil1611 requested changes
Good Work @aneenajohn 

Here are my few suggestions:

2021-05-14 08:23 UTC, Jaynil1611 commented on src/App.jsx
> +import { DataLoader } from "./components/DataLoader";
- Inside the components folder make an `index.js` file which re-exports all files inside components, so similarly create such file for nested folders you create
```suggestion
import ProductList from "./components";
```

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/DataLoader.js
> +  }, []);
Combine it in a single useEffect, you can write both functions in one effect

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/Filter/sort.js
> +  return productList;
Remove `console.log()` statements  & comments from everywhere. Also instead of using multiple if you can use a switch statement here,

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/ProductList/productContext.js
> +          showFastDeliveryOnly: state.showFastDeliveryOnly,
No need to destructure the state here, you can do it in the components directly
```suggestion
          state,
```

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/ProductList/productList.js
> +import { useState, useEffect } from "react";
Split this file into separate files, extract handlers into different file

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/WishList/wishReducer.js
> +        )
Extract this into a pure function and use it here

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/WishList/wishReducer.js
> +export const wishReducer = (state, action) => {
destructure action into `{type, payload}`

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/WishList/wishReducer.js
> +              offer: action.payLoad.offer
Instead of iterating on each property use spread operator
```suggestion
          ...payload
```

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/cart/cartList.js
> +  const totalReducer = () =>
Rename it to `totalPrice`

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/ProductList/productList.js
> +                  </div>
Remove unnecessary spacings and braces

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/cart/cartList.js
> +      };
You can omit this and use the updated response coming from the backend as a payload

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/cart/cartList.js
> +
This function is the same as used in `productList.js`. Try not to repeat yourself

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/cart/cartList.js
> +import { useCart } from "./cartContext";
Split this long file into different files

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/cart/cartReducer.js
> +              offer: action.payLoad.offer
Use spread operator as mentioned in above reducer as well

2021-05-14 08:23 UTC, Jaynil1611 commented on src/components/cart/cartReducer.js
> +      };
Extract this into a function and use here

2021-05-20 07:37 UTC, Aravindan07 requested changes
Great work aneena! I gave some suggestions/changes for your app.

1. Reduce the box-shadow on the card hover.
2. Change the cursor to a pointer on the wishlist icon present in the card. Same for clear all option too in the filter.
3. Hover effect is present only on the cart icon in the navbar do it for the wishlist icon too.
4. It shows a message like **added to cart item-name** for out-of-stock items.
5. Pictures in the empty cart list and empty wishlist are too big I think. This is just a suggestion if you want you can change it.
6. There is an empty file called cartUpdates.js if you are to using it remove it.
7. Remove commented code present in your source code.
8. On reloading the page other than the home page your application breaks. This can be fixed by adding _redirects file.

2021-05-20 07:37 UTC, Aravindan07 commented on package.json
> +    "faker": "5.5.3",
You are not using faker,mirageJS, web vitals packages I hope. If so please uninstall it.

2021-05-20 07:37 UTC, Aravindan07 commented on src/data.js
> +//           </Link>
This whole file is commented on, if you are not using it remove it.

2021-05-20 07:37 UTC, Aravindan07 commented on src/App.jsx
> +// import ProductList from "./components/Products";
Again remove comments if you are not using them anywhere in your application.

2021-05-20 07:37 UTC, Aravindan07 commented on src/components/backendUrl.js
> +export const BACKEND_URL = "https://lingokart-api.aneenasam.repl.co/";
Pushing the backend URL and any other secrets to GitHub is not advisable. Use a .env file for these.

2021-05-20 07:37 UTC, Aravindan07 commented on src/components/DataLoader.js
> +      console.log("cart data", data);
Remove logs whenever you push your application to deployment.

2021-05-20 07:37 UTC, Aravindan07 commented on src/components/ProductList/productList.js
> +                name="sort"
Extract the filter component into a separate component and consume it here it will reduce the number of lines in this file also code looks cleaner.

2021-05-20 07:37 UTC, Aravindan07 commented on src/components/ProductList/productList.js
> +                      <strong>{getTrimmedTitle(data.name)}</strong>
Same for card component too extract this in a separate component and consume it like,
 ``` filteredData.map((data) => ( <Card someProps={data} />)```

2021-05-20 07:37 UTC, Aravindan07 commented on src/components/ProductList/productList.js
> +            </div>
Same for spinner too. In this way, you can reuse components wherever you want your application

2021-05-20 07:37 UTC, Aravindan07 commented on src/components/cart/cartList.js
> +                    </h1>
See you are using the same card component used in the product list page here. Extract it and use it as a separate component and reuse it wherever you want.

2021-05-20 07:37 UTC, Aravindan07 commented on src/components/utils/utils.js
> +    var trimmedTitle = title.substr(0, 25);
Use let instead of var

2024-01-20 07:48 UTC, merged